import { createSlice } from '@reduxjs/toolkit';

// Define the initial state of the order creation
const initialState = {
  order: null,
  loading: false,
  error: null,
  success: false,
};

// Create a slice for order creation
const orderCreateSlice = createSlice({
  name: 'orderCreate',
  initialState,
  reducers: {
    // Action to start order creation
    orderCreateRequest(state) {
      state.loading = true;
    },
    // Action for successful order creation
    orderCreateSuccess(state, action) {
      state.loading = false;
      state.success = true;
      state.order = action.payload;
    },
    // Action for failed order creation
    orderCreateFail(state, action) {
      state.loading = false;
      state.error = action.payload;
    },
    // Action to reset order creation state
    orderCreateReset(state) {
      state.order = null;
      state.loading = false;
      state.error = null;
      state.success = false;
    },
  },
});

// Export the actions generated by createSlice
export const {
  orderCreateRequest,
  orderCreateSuccess,
  orderCreateFail,
  orderCreateReset,
} = orderCreateSlice.actions;

// Export the reducer to be used in the store
export default orderCreateSlice.reducer;
